export const FETCH_CRYPTO_LOADING = 'FETCH_CRYPTO_LOADING';
export const FETCH_CRYPTO_SUCCESS = 'FETCH_CRYPTO_SUCCESS';
export const FETCH_CRYPTO_FAIL = 'FETCH_CRYPTO_FAIL';
export const REMOVE_CRYPTO_TOKEN = 'REMOVE_CRYPTO_TOKEN';
export const ADD_CRYPTO_TOKEN = 'ADD_CRYPTO_TOKEN';
export const ADD_CRYPTO_FAIL = 'ADD_CRYPTO_FAIL';
